from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from ..models import Artifact, PostDraft, PostPublication
from ..publishers.facebook import FacebookAdapter
from ..publishers.instagram import InstagramAdapter
from ..publishers.x import XAdapter
from ..publishers.fanvue import FanvueAdapter
from ..services.fanvue_oauth import FanvueOAuth
from ..services.s3_media_storage import S3MediaStorage


@dataclass
class DailyFragmentPackage:
    title: str
    body: str
    x_body: str
    fanvue_body: str
    public_image_path: Path
    fanvue_image_path: Path
    content_tags: list[str] = field(default_factory=lambda: ["recovered-fragment", "identity", "echo-traversal"])


def default_daily_fragment_run_id(now=None):
    current = now or datetime.now().astimezone()
    return current.strftime("%Y%m%dT%H%M%S%f")


def publish_daily_fragment_package(session, config, package, local_date, run_id=None, allow_dry_run=False):
    facebook = FacebookAdapter()
    instagram = InstagramAdapter(
        user_id=config.get("INSTAGRAM_USER_ID"),
        access_token=config.get("INSTAGRAM_ACCESS_TOKEN"),
        graph_version=config.get("INSTAGRAM_GRAPH_VERSION"),
        media_base_url=config.get("INSTAGRAM_MEDIA_BASE_URL"),
        dry_run=config.get("INSTAGRAM_DRY_RUN"),
    )
    x_publisher = XAdapter(
        consumer_key=config.get("X_CONSUMER_KEY"),
        consumer_secret=config.get("X_SECRET_KEY"),
        access_token=config.get("X_ACCESS_TOKEN"),
        access_token_secret=config.get("X_ACCESS_TOKEN_SECRET"),
        bearer_token=config.get("X_BEARER_TOKEN"),
        username=config.get("X_USERNAME"),
        dry_run=config.get("X_DRY_RUN"),
    )
    fanvue = FanvueAdapter(
        oauth=FanvueOAuth(
            client_id=config.get("FANVUE_CLIENT_ID"),
            client_secret=config.get("FANVUE_CLIENT_SECRET"),
            redirect_uri=config.get("FANVUE_REDIRECT_URI"),
            token_path=config.get("FANVUE_TOKEN_PATH"),
        ),
        api_version=config.get("FANVUE_API_VERSION"),
        audience=config.get("FANVUE_AUDIENCE"),
        dry_run=config.get("FANVUE_DRY_RUN"),
    )
    if (facebook.dry_run or instagram.dry_run or x_publisher.dry_run or fanvue.dry_run) and not allow_dry_run:
        raise ValueError("Facebook, Instagram, X, and FanVue must all be configured for live publishing.")

    run_id = str(run_id or default_daily_fragment_run_id()).strip()
    fragment_code = f"daily-fragment-run-{run_id}"
    storage = S3MediaStorage(
        bucket=config.get("S3_MEDIA_BUCKET"),
        region=config.get("S3_MEDIA_REGION"),
        prefix=config.get("S3_MEDIA_PREFIX"),
        presign_seconds=config.get("S3_PRESIGN_SECONDS"),
    )
    stored = storage.store_instagram_image(
        package.public_image_path,
        package.title,
        local_day=local_date,
        output_dir=config.get("UPLOAD_FOLDER"),
    )

    artifact = session.query(Artifact).filter_by(fragment_code=fragment_code).one_or_none()
    metadata = dict((artifact.generated_metadata if artifact else {}) or {})
    metadata.update(
        {
            "run_id": run_id,
            "local_date": local_date.isoformat(),
            "s3_bucket": config.get("S3_MEDIA_BUCKET"),
            "s3_object_key": stored.object_key,
            "public_media_url": stored.signed_url,
            "fanvue_media_path": str(package.fanvue_image_path.resolve()),
        }
    )
    if artifact is None:
        artifact = Artifact(
            title=package.title,
            artifact_type="text_fragment",
            summary=package.body,
            lore_text=package.body,
            visibility="public",
            fragment_code=fragment_code,
            canonical_status="generated_artifact",
            source_notes="Generated by the daily recovered-fragment automation.",
            content_tags=package.content_tags,
        )
        session.add(artifact)
    artifact.original_filename = stored.local_path.name
    artifact.media_path = str(stored.local_path.resolve())
    artifact.media_content_type = stored.content_type
    artifact.media_size = stored.local_path.stat().st_size
    artifact.generated_metadata = metadata
    artifact.platform_tags = ["facebook", "instagram", "x", "fanvue"]
    session.flush()

    drafts = {draft.platform: draft for draft in artifact.post_drafts}
    platform_bodies = {
        "facebook": package.body.strip(),
        "instagram": package.body.strip(),
        "x": package.x_body.strip(),
        "fanvue": package.fanvue_body.strip(),
    }
    for platform in ("facebook", "instagram", "x", "fanvue"):
        if platform not in drafts:
            drafts[platform] = PostDraft(
                artifact=artifact,
                platform=platform,
                caption=platform_bodies[platform],
                hashtags=[],
                call_to_action="",
                status="approved",
                approved_at=datetime.now(timezone.utc),
            )
            session.add(drafts[platform])
        else:
            drafts[platform].caption = platform_bodies[platform]
    session.commit()

    urls = []
    errors = []
    for platform, adapter in (
        ("facebook", facebook),
        ("instagram", instagram),
        ("x", x_publisher),
        ("fanvue", fanvue),
    ):
        draft = drafts[platform]
        already_published = any(
            publication.status == "published" and publication.external_post_id
            for publication in draft.publications
        )
        if already_published:
            publication = next(
                publication
                for publication in draft.publications
                if publication.status == "published" and publication.external_post_id
            )
            urls.append(f"{platform}: {publication.external_url or publication.external_post_id}")
            continue

        result = adapter.publish(draft)
        draft.status = result.status
        session.add(
            PostPublication(
                post_draft=draft,
                platform=platform,
                status=result.status,
                external_post_id=result.external_post_id,
                external_url=result.external_url,
                error_message=result.error_message,
                raw_response=result.raw_response,
            )
        )
        session.commit()
        if result.success:
            urls.append(f"{platform}: {result.external_url or result.external_post_id}")
        else:
            errors.append(f"{platform}: {result.error_message or 'publish failed'}")

    return artifact, run_id, urls, errors
